/*
 * This code was generated by FormatTemplate as part of the build process. Do not edit it.
 *
 * Generated on 2016-05-02 03:00:46.
 *
 */

namespace IronPython {
    public static class CurrentVersion {
        public const int Major = 3;
        public const int Minor = 0;
        public const int Micro = 0;
        public const string ReleaseLevel = "alpha";
        public const int ReleaseSerial = 0;

        public const string ShortReleaseLevel = "a";

        public const string Series = "3.0";
        public const string DisplayVersion = "3.0.0a0";
        public const string DisplayName = "IronPython 3.0.0a0";

        public const string AssemblyVersion = "3.0.0.0";
        
        public const string AssemblyFileVersion = "3.0.0.0000";
        public const string AssemblyInformationalVersion = "IronPython 3.0.0 alpha 0";
    }
}
